[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
conditions = {Not = [IsFile]}

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"